meta:
  app_id: cmp_library_plan_opal_tool
  display_name: CMP Library and Plan Opal Tool WI
  version: 1.0.0-dev.14
  vendor: optimizely
  summary: Opal tool to perform action within CMP Library and Plan Module
  support_url: https://support.optimizely.com
  contact_email: support@optimizely.com
  categories:
    - Marketing
    - Opal
  availability:
    - all

runtime: node22

functions:
  opal_tool:
    entry_point: OpalCMPToolFunction
    description: Opal CMP Tool Function
  
